### PR TITLE
Fix compatibility and crashes with OBS 29.1.2

### PR DESCRIPTION
**Pull request by ujifgc**
This PR fixes 3 things:

1) replaces deprecated calls to API

2) fixes crash on loading filter properties. This was probably introcuded with https://github.com/obsproject/obs-studio/commit/78aa4e03dca62c3e1439cae2eade1c6d247c8a78

Downside of this fix is that now the user has to re-select filter page after changing the encoder. Current OBS API does not fully support property callbacks despite stating in the documentation https://docs.obsproject.com/reference-properties#c.obs_property_set_modified_callback2

3) fixes crash on changing source resolution. It seems that creating a thread with closing routines causes racing condition. When calling routines directly it works fine and the recording restarts properly.

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Excellent work @ujifgc 

I'm using your fixes branch in my build system for OBS Studio (and many plugins) that compiles OBS Studio from source for multiple Ubuntu releases. Your changes address some FTBFS issues :+1:

**Comment by jprobichaud** [comment]
I hope this gets picked soon, getting to 29.1.2 was nice for a bunch of new features, but the fact the the plugin breaks here is really messing up with our workflow

**Comment by exeldro** [comment]
The deprecated call are needed to keep supporting older versions of OBS.
OBS 29.1.3 has a fix for the properties of source record.

**Comment by customswitch** [comment]
Can someone compile it for me? I don't know how to do that. I'm using Windows x64.

**Comment by jaminmc** [comment]
I think this PR is obsolete now, as Source-Record supports up to 30.0.2. Currently, it causes an issue because the recordings don't stop when they are stopped. but that is being worked on)

**Pull request closed without merging**
